### ISSUE TITLE
Bug with Artifact Weapon

### ISSUE THREAD

**Issue by Kleei** [MrTheSoulz/NerdPack#218] opened 2017-06-26 09:32 UTC
Bug with Artifact Weapon , can't open. It just becomes gray from start and can't shift+ right clicking on it. Client version 7.1.5 23420. NerdPack up to date
![wowscrnshot_062617_122506](https://user-images.githubusercontent.com/29488485/27534385-77f77e64-5a6f-11e7-9994-174d81cfe3e9.jpg)

**Comment by adde88** [comment] 2017-06-26 10:40
Please post LUA error messages (if any), it makes it alot easier to debug stuff like this.
And try to describe the error-situation as thoroughly as possible, don't skip any details.

**Comment by Kleei** [comment] 2017-06-26 11:24
I didn't noticed any errors , just like you see it's gray and can't open it and that's all. When disable the addon all it's ok and when enable it Artifact Weapon becomes gray , that's all i can tell.

**Comment by zy4944796** [comment] 2017-06-26 18:25
@adde88 please tell me where is the lua error file I can find?

**Comment by Kleei** [comment] 2017-06-28 21:51
>adde88 : Please post LUA error messages

there you go

> 1x ...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0-16.lua:174: attempt to index local 'info' (a number value)
> ...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0-16.lua:174: in function <...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:167>
> ...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0-16.lua:242: in function <...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:233>
> ...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0-16.lua:258: in function <...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:254>
> ...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0-16.lua:321: in function `?'
> ...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0-16.lua:68: in function <...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:68>
> 
> Locals:
> artifactID = nil
> traits = <table> {
> }
> powers = <table> {
>  1 = 125
>  2 = 126
>  3 = 127
>  4 = 128
>  5 = 129
>  6 = 130
>  7 = 131
>  8 = 132
>  9 = 133
>  10 = 134
>  11 = 135
>  12 = 136
>  13 = 137
>  14 = 138
>  15 = 139
>  16 = 140
>  17 = 1335
>  18 = 1367
> }
> (for index) = 1
> (for limit) = 18
> (for step) = 1
> i = 1
> traitID = 125
> info = 208253
> (*temporary) = 125
> (*temporary) = 208253
> (*temporary) = 64800
> (*temporary) = 1
> (*temporary) = 1
> (*temporary) = 0
> (*temporary) = 0.27793097496033
> (*temporary) = "attempt to index local 'info' (a number value)"
> GetPowers = <function> defined =[C]:-1
> GetPowerInfo = <function> defined =[C]:-1
> GetSpellInfo = <function> defined =[C]:-1
> artifacts = <table> {
>  knowledgeMultiplier = 1
>  knowledgeLevel = 0
> }
>

**Comment by adde88** [comment] 2017-06-29 06:46
What rotation are you using when this is happening?
I believe it could be related to some custom function/condition within that developers routine which triggers this bug of yours.

**Comment by Kleei** [comment] 2017-06-29 08:35
adde88 , i use NeP + my own CR.  I don't use any artifact condition and i don't use any foreign files core. I use only generic condition from NeP. All other addon's are disabled, only NeP + my CR are active.

**Comment by MrTheSoulz** [comment] 2017-07-02 16:39
Im unable to reproduce this error, sorry.
Make sure no ther addon is messing with artifacts and that you'r on live wow.
Closing this until someone else confirms this issue...

**Closed** 2017-07-11 19:59 UTC
