### ISSUE TITLE
Holy priest rotation is not using renew on raid targets

### ISSUE THREAD

**Issue by Chiisato** [MrTheSoulz/NerdPack#19] opened 2015-11-01 19:03 UTC
As said, it does not cast renew on raid targets, no matter what I set the value at. It only keeps the buff up on tanks/focus target and myself/the player.

**Comment by MrTheSoulz** [comment] 2015-11-01 22:30
I've looked at the code and since its a bit old and i do things more 'cleaner' now, ive decided to refactor it.
Intial commit: 87a1fbe21fbfaa2485d8f3b8bfa4810c3a7b59af

This should be fixed once i finish it,
Will leave this open until i've comfirmed its fixed.

Thanks, 
MTS.

**Comment by Chiisato** [comment] 2015-11-02 10:36
I'll give this a go in LFR and see if I notice any improvement, thanks!

**Comment by Chiisato** [comment] 2015-11-02 17:35
Did some LFR with the initial commit you linked,  still no renews on raid no matter what I set the value at

**Comment by Chiisato** [comment] 2015-11-03 20:01
Interface\AddOns\NerdPack\rotations\priest\holy.lua:265: bad argument #2 to 'min' (number expected, got nil)

This is in the _PoH function, line 265 is "				subgroups[subgroup] = subgroups[subgroup] + min(minHeal, ProbablyEngine.raid.roster[i].healthMissing)" for me

**Comment by MrTheSoulz** [comment] 2015-11-03 21:20
That error is unrelated to this issue and should not affect the CR.

**Comment by MrTheSoulz** [comment] 2015-11-03 22:19
Ive confirmed the Renew issue and it seems like "!lowest.buff(#)" is not working correctly.
This is a PE issue, since it fails no matter what buff ID i insert in it (the shield does not work on raid (lowest) either).

Also i noticed it would not matter much anyway since lowest includes Tank & Focus, so unless a raid member is bellow those units on health it would not cast anyway.

This can only be fixed by creating a new heal engine.

**Comment by Chiisato** [comment] 2015-11-04 13:00
I see, that's a shame. Thanks for confirming it!

**Closed** 2015-11-07 16:24 UTC
Labels: bug, WontFix
