### ISSUE TITLE
CR gets stuck trying to use an item and fails

### ISSUE THREAD

**Issue by heistcode** [MrTheSoulz/NerdPack#144] opened 2016-11-07 04:20 UTC
Sometimes http://www.wowhead.com/item=132510 will go onto cooldown but the UI won't show it. It may even return that it's off cooldown if you use GetItemCooldown (not sure) but it fails to cast because it's on CD.

The CR locks up when this happens.

**Comment by buginote** [comment] 2016-11-07 04:38
Indeed ,this item has cooldown bug.Maybe Blizzard did this on purpose--the bomb should not to be expected used in General dps routine.
I have give up to use this item in CR

**Comment by MrTheSoulz** [comment] 2016-11-07 12:36
I saw this with healthstone, i couldnt figure out a way around it.
it seems like certain items dont return the cooldown correctly :/

**Comment by modhunter** [comment] 2016-11-07 13:44
I don't know if something was changed in 7.0 to break this, but this functionality worked correctly in the old probablyengine during warlords.  It may be worth taking a look at the old code to see how item usage was implemented for any hints.

**Comment by MrTheSoulz** [comment] 2016-11-07 15:05
@modhunter it sohuld be working find, its some bug in wow's apis (GetItemCooldown).
I noticed it only accepts ID's even tho the docs say it should accept names aswell.
PE should be affected aswell if this is the case.

**Comment by heistcode** [comment] 2016-11-07 15:28
Won't fix? There is an event when a spell fails to cast. Isn't there one when an item fails to be used? You could blacklist the item.

If not can't we check how long we've been attempting to do something? If an item doesn't cast when it is off cooldown and the GCD is over we don't really need to even give it that much of a grace period. We should just move on for a whole rotation.

If I use a macro will the CR lock up or continue on?

This isn't related to incorrect GetItemCooldown usage because it works sometimes and I have a WeakAura that uses an itemID. All API calls show the item off cooldown and all the things it shares a cooldown with presumably because if you open your bags it shows the items not on cooldown even though you just used it and can't use it again.

**Comment by MrTheSoulz** [comment] 2016-11-07 17:47
i guess we could blacklist something that tries to cast more then (x10) times in a row?

**Comment by modhunter** [comment] 2016-11-12 06:02
I got this error today in raid when I think my CR attempted to use an item like a healthstone or a healing potion.  

The error was: `actions.lua:92: Usage: GetItemCooldown(itemID)`  It caused the CR to completely stop and only give the error after combat was over :(

The lines in my CR that probably attempted to use the items were:
```
{ '#5512', 'player.health <= UI(Healthstone)', "player" }, -- Healthstone
{ "#109223", 'player.health <= UI(Healthstone)', "player" }, -- Healing Tonic
```

For now i've commented this out, but it would be great if it didn't error and even better if we could actually use items!

**Comment by MrTheSoulz** [comment] 2016-11-12 12:11
That error should be fixed in master by @heistcode.

**Comment by modhunter** [comment] 2016-11-13 03:01
@MrTheSoulz FYI this error occurred while running fe7e863 which includes the change made by Heist in 6678a41.

**Comment by heistcode** [comment] 2016-11-13 03:11
This happened in combat? https://github.com/MrTheSoulz/NerdPack/issues/146 occurred during compile. Your error might be something else. If you got to line 92 that must mean the 'item' table had an 'id' key... We'd need the whole bug report to see what that 'id' was.

**Comment by heistcode** [comment] 2016-11-13 03:33
Here's two events that fire when a item fails to cast:
Removed stuff specific to my character
COMBAT_LOG_EVENT_UNFILTERED
arg 1: *timestamp*
arg 2: "SPELL_CAST_FAILED"
arg 4: *caster GUID*
arg 5: *caster name*
arg 6: *caster flags*
arg 7: *caster raid flags*
arg 8: ""
arg 10: "-2147483648"
arg 11: "-2147483648"
arg 12: "200285"
arg 13: "Gunpowder Charge"
arg 14: 4
arg 15: "Item is no ready yet"

UNIT_SPELLCAST_FAILED
arg 1: "player"
arg 2: "Gunpowder Charge"
arg 3: ""
arg 4: *lineID*
arg 5: 200285

Mind you, both of these fired when the UI was actually aware of the item being on cooldown. I wasn't able to test that these two event fire in the event of this bug occurring.

**Comment by modhunter** [comment] 2016-11-13 15:44
It was strange because the LUA error that popped up did not include any values of any variables (i.e. `id`).  It was most alarming because it occurred during a raid encounter and the CR completely stopped until a `/reload` after combat was over.

For now, I'm not including anything in my CRs that attempt to use an item (things that start with `#`) because of this which happened two different times.

**Comment by MrTheSoulz** [comment] 2016-11-13 17:15
@modhunter If im correct, that error should be fixed now...
Im now working on a blacklist using the event @heistcode provided.

**Comment by MrTheSoulz** [comment] 2016-11-13 18:35
Sent a commit that should blacklist items when they fail, i havent tested it yet tho

**Comment by modhunter** [comment] 2016-11-15 02:20
I tried to reproduce this at a tanking training dummy and it didn't appear to try to use an item at all anymore, so I think it's fixed? :)

It would be so cool if we could get auto-item (health pot & healthstone) usage working though

**Comment by MrTheSoulz** [comment] 2016-11-15 07:43
Should be, pots and healthstone too, no?
The items get blacklisted when failed

**Comment by modhunter** [comment] 2016-11-15 15:56
Will test again.  I just realize that the healing potion I have is the wrong one for Legion

**Comment by modhunter** [comment] 2016-11-18 03:55
I can confirm that it is working correctly w/Ancient Healing Potion:

`{ "#127834", 'player.health <= UI(Healthstone)', "player" }, -- Ancient Healing Potion`

Fires correctly and the CR continues.  IMO you can close this.

**Comment by modhunter** [comment] 2016-11-18 04:36
Tested and verified that it works on a training dummy using Ancient Healing Potion (127834):
`{ "#127834", 'player.health <= UI(Healthstone)', "player" }`

However, in a dungeon, it seems to have errored again on a warlock healthstone (5512)
`{ '#5512', 'player.health <= UI(Healthstone)', "player" }`

with the following error:

```
Message: Interface\AddOns\NerdPack\system\actions.lua:92: Usage: GetItemCooldown(itemID)
Time: Thu Nov 17 23:14:50 2016
Count: 1
Stack: [C]: ?
[C]: ?
Interface\AddOns\NerdPack\system\actions.lua:92: in function <Interface\AddOns\NerdPack\system\actions.lua:88>
(tail call): ?
Interface\AddOns\NerdPack\system\parser.lua:97: in function `Parse'
Interface\AddOns\NerdPack\system\parser.lua:90: in function `Parse'
Interface\AddOns\NerdPack\system\parser.lua:128: in function <Interface\AddOns\NerdPack\system\parser.lua:121>
Interface\SharedXML\C_TimerAugment.lua:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals: 
```

**Comment by modhunter** [comment] 2016-11-23 13:19
FYI, something changed after commit ed7fc5a made this stop working at least for healing potions.

I have a pretty simple test by which I call `{ "#127834", 'player.health <= UI(Healthstone)', "player" }` with the UI setting threshhold set to 100, and then enter combat with a tanking training dummy.

In commit ed7fc5a this works.  In the latest commit (1f17c56) this does not work anymore (no errors - it simply doesn't even attempt to use the item).

For reference, here are the commits since ed7fc5a:

```
* 2016-11-19 1f17c56 (HEAD -> master, upstream/master) fix Al  [Jaime Marques]
* 2016-11-19 63f3ad8 fix targets  [Jaime Marques]
* 2016-11-19 e4ed1a9 healing test  [Jaime Marques]
* 2016-11-19 5d72aee name error  [Jaime Marques]
* 2016-11-19 d747caa remove rar file  [Jaime Marques]
* 2016-11-19 73078b6 fix apply text  [Jaime Marques]
* 2016-11-16 ed7fc5a (tag: working_1.8) Minor additions (#152)  [Yobleed]
```

**Comment by heistcode** [comment] 2016-11-23 13:50
I've noticed the CR struggling with items too. Occasionally this would work but not every time:
	{"#139326", "equipped(139326) & !player.buff(Combustion)"},
Same with HP potions.

**Comment by modhunter** [comment] 2016-12-07 22:07
@vorus do you mind taking a look at this one too since you're fixing things?

**Comment by Yobleed** [comment] 2016-12-11 17:13
Items are not getting blacklisted.

**Closed** 2017-01-18 22:37 UTC
Labels: bug, wontfix
